export const list_api = {
  title: "列表接口",
  url: "/receivable/queryMonthSummaryList",
  method: "post",
  data: {},
};
export const export_api = {
  title: "导出接口",
  url: "/receivable/exportMonthSummary?",
  method: "get",
};

export const buTypeList = [
  { label: "国内短信", value: 1 },
  { label: "国际短信", value: 2 },
  { label: "万数", value: 3 },
];
export const table_columns = [
  {
    title: "统计月份",
    key: "billMonth",
    width: 80,
    dataIndex: "billMonth",
    search: false,
  },
  {
    title: "统计月份",
    key: "billMonth",
    width: 110,
    dataIndex: "billMonth",
    valueType: "dateRange",
    fixed: "left",
    fieldProps: {
      format: "YYYY-MM",
      picker: "month",
    },
    hideInTable: true,
    search: {
      transform: (value) => {
        if (value) {
          return {
            billStartDate: value[0].split("-").join(""),
            billEndDate: value[1].split("-").join(""),
          };
        }
      },
    },
  },
  {
    title: "客户名称",
    key: "customerName",
    width: 240,
    dataIndex: "customerName",
    search: true,
    fixed: "left",
    ellipsis: true,
    copyable: true,
  },
  {
    title: "账号",
    key: "primaryApiAccount",
    width: 130,
    dataIndex: "primaryApiAccount",
    search: true,
    fixed: "left",
    ellipsis: true,
    copyable: true,
  },
  {
    title: "产品大类",
    key: "buType",
    width: 90,
    dataIndex: "buType",
    search: false,
    valueType: "select",
    fieldProps: {
      options: buTypeList,
    },
  },
  {
    title: "产品名称",
    key: "productName",
    width: 110,
    dataIndex: "productName",
    ellipsis: true,
    search: false,
  },
  {
    title: "负责人",
    key: "chargePerson",
    width: 70,
    search: false,
    ellipsis: true,
    dataIndex: "chargePerson",
  },
  {
    title: "运维人",
    key: "operationPerson",
    width: 70,
    search: false,
    ellipsis: true,
    dataIndex: "operationPerson",
  },
  {
    title: "销售人",
    key: "salePerson",
    width: 70,
    search: false,
    ellipsis: true,
    dataIndex: "salePerson",
  },
  {
    title: "期初余额",
    key: "openAmount",
    width: 90,
    ellipsis: true,
    search: false,
    dataIndex: "openAmount",
  },
  {
    title: "本期消耗",
    key: "consumeAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "consumeAmount",
  },
  {
    title: "本期销账",
    key: "writeOffAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "writeOffAmount",
  },
  {
    title: "本期回款",
    key: "returnAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "returnAmount",
  },
  {
    title: "本期结余",
    key: "remainAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "remainAmount",
  },
  {
    title: "销账",
    key: "allWriteOffAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "allWriteOffAmount",
  },
  {
    title: "回款",
    key: "allReturnAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "allReturnAmount",
  },
  {
    title: "期末余额",
    key: "closeAmount",
    ellipsis: true,
    width: 90,
    search: false,
    dataIndex: "closeAmount",
  },
  {
    title: "账龄",
    // key: "accountAge",
    search: false,
    children: [
      {
        title: "0-30 天",
        key: "firstMonthAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "firstMonthAmount",
      },
      {
        title: "31-60 天",
        key: "secondAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "secondAmount",
      },
      {
        title: "61-90 天",
        key: "thirdAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "thirdAmount",
      },
      {
        title: "91-120 天",
        key: "forthAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "forthAmount",
      },
      {
        title: "121-180 天",
        key: "fifthSixthAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "fifthSixthAmount",
      },
      {
        title: "181-360 天",
        key: "seventhTwelfthAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "seventhTwelfthAmount",
      },
      {
        title: "1-2 年",
        key: "secondYearAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "secondYearAmount",
      },
      {
        title: "2-3 年",
        key: "thirdYearAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "thirdYearAmount",
      },
      {
        title: "3年以上",
        key: "aboveThirdYearAmount",
        ellipsis: true,
        width: 90,
        dataIndex: "aboveThirdYearAmount",
      },
    ],
  },
  {
    title: "生成时间",
    key: "createDateStr",
    width: 90,
    search: false,
    dataIndex: "createDateStr",
  },
];
